### ISSUE TITLE
Convert this to a backend plugin

### ISSUE THREAD

**Issue by TheSpiderPig** [brianium/watermarkjs#11]
Convert this into a backend plugin so that with nodejs we can watermark the image before download time. 

Ideally this would become a part of a grunt or gulp task automation tool.

**Comment by brianium** [comment]
Hmmm... that's really not in the spirit of the project, but it seems like an option. I am wondering if this library could take a little more care in checking for window before adding `watermark` to it so other libraries can more easily consume the main export.

```js
//index.js
if (typeof(window) !== 'undefined') {
  window.watermark = watermark;
}
```

Then it might be possible to write a standalone gulp/grunt plugin that leverages a tool like [node-canvas](https://github.com/Automattic/node-canvas) - since watermark.js relies heavily on canvas for image manipulation.

Thoughts?

**Comment by ayancey** [comment]
watermarkjs seems heavily limited if it can be easily circumvented by downloading the image directly.

**Comment by brianium** [comment]
Yes - this definitely applies when using urls or existing images as resources for watermarking. However when using file inputs, it cannot be circumvented. It becomes really useful when you need to generate watermark images based on uploads - see the example [here](http://brianium.github.io/watermarkjs/uploading.html). 

Watermarking on the server has been around for some time, and it is a useful technique. A client side solution becomes preferable when:

1. Your host may or may not have image libraries (shared hosting)
2. Your host doesn't have a good way to batch uploads (shared hosting, limited php install?)

You cannot circumvent the process when the watermark is generated from an uploaded image - or at least not by any means I am aware of :)

**Comment by ayancey** [comment]
In that case, I totally agree. Other backend libraries for watermarking images already exist, and this looks like it fills a niche. :+1:

**Comment by brianium** [comment]
:+1:

**Comment by brianium** [comment]
I think I am going to close this issue. If someone wants to submit a PR to make the library work server side, I would definitely consider it. The point of the library as is, is to be a client side watermarking solution (for all the reasons discussed)
